version: 2

jobs:
  server_build_and_check:
    docker:
      # TODO use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:latest

    steps:
      - checkout
      - run: git submodule update --init # TODO eh, this is only needed for integration tests...

      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "wereyouhere/requirements.txt" }}-{{ checksum "wereyouhere/requirements-dev.txt" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-

      - run: python3 -m pip install --user tox
      # ugh, hug is involved as subprocess and doesn't see virtualenv I gues??
      - run: python3 -m tox

      # - save_cache:
      #     paths:
      #       - ./venv
      #     key: v1-dependencies-{{ checksum "wereyouhere/requirements.txt" }}-{{ checksum "wereyouhere/requirements-dev.txt" }}
        

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
  client_build_and_check:
    docker:
      - image: circleci/node:latest
    working_directory: ~/project/extension # https://stackoverflow.com/a/50570581/706389
    steps:
      - checkout:
          path: ~/project

      # TODO not sure if should update shallalist?
      - run: npm install
      - run:
          name: build
          command: ./build --firefox --release
      - run:
          name: js flow
          command: npm run flow # TODO use flow discovery or something??
          when: always 
      - run:
          name: js eslint
          command: npm run eslint
          when: always 
      - run:
          name: tests
          command: npm run test
          when: always
      # TODO pack?


workflows:
  version: 2
  build_and_test:
    jobs:
      - client_build_and_check
      - server_build_and_check
