# see https://github.com/karlicoss/pymplate for up-to-date reference

name: CI
on: [push]

env:
  # for tests
  # not sure if tests should detect GITHUB_WORKFLOW instead??
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
     
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - run: echo "::add-path::$HOME/.local/bin"

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2
      with:
        submodules: recursive
   
    # uncomment for SSH debugging
    # - uses: mxschmitt/action-tmate@v2

    - run: scripts/ci/run

  install_and_run_test:
    # TODO use setup-python thing?
    # TODO run on macos too?
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: ci/github-ci-compat

    - run: |
        python3 -m pip install .
        export PATH=ci/fake-systemd:$PATH
        tests/install_and_run

  run_demo:
    strategy:
      matrix:
        # TODO this should def just run on either platform
        platform: [macos-latest] # ubuntu-latest,
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    # uncomment to debug via SSH
    # - uses: mxschmitt/action-tmate@v2
    - run: |
        pip3 install --user promnesia

        # TODO ugh. that action was meant to set up PATH, but it's still not there :(
        # /Users/runner/Library/Python/3.7/bin

        # no idea why that's not in PATH either...
        /Users/runner/.local/bin/promnesia demo --port 16789 https://github.com/karlicoss/exobrain & \
           sleep 10 && curl 'http://localhost:16789/search' --data 'url=github.com'

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - run: |
        # just index
        pip3 install --user .
        pip3 install --user .[org] # just so it doesn't spam
        scripts/promnesia demo https://github.com/karlicoss/exobrain

  pypi:
    runs-on: ubuntu-latest
    needs: [build, install_and_run_test, run_demo]

    steps:
    - run: echo "::add-path::$HOME/.local/bin"

    - uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: 'release to test pypi'
      # always deploy merged master to test pypi
      if: github.event.ref == 'refs/heads/master'
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD_TEST }}
      run: pip3 install --user wheel twine && scripts/release --test

    - name: 'release to pypi'
      # always deploy tags to release pypi
      # TODO filter release tags only?
      if: startsWith(github.event.ref, 'refs/tags')
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: pip3 install --user wheel twine && scripts/release
